# cargo

# [[file:~/Workspace/Programming/structure-predication/spdkit/spdkit.note::*cargo][cargo:1]]
[package]
name = "spdkit"
version = "0.0.14"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
gchemol = { git = "https://github.com/ybyygu/gchemol.git", tag="v0.0.35" }
#gchemol = {path = "/home/ybyygu/Workspace/Programming/gchemol-rs/gchemol/gchemol"}
rand = "0.7"
quicli = "0.4"
lazy_static = "1.3"
# cargo:1 ends here
