# cargo

# [[file:~/Workspace/Programming/structure-predication/spdkit/spdkit.note::*cargo][cargo:1]]
[package]
name = "spdkit"
version = "0.0.2"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
gchemol = { path = "../../gchemol" }
#gchemol = { git = "https://github.com/ybyygu/gchemol.git" }
quicli = "0.3"
# cargo:1 ends here
